CREATE DATABASE palavras_cruzadas;

USE palavras_cruzadas;

CREATE TABLE palavras_cruzadas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    palavra VARCHAR(7) NOT NULL,
    dica VARCHAR(50) NOT NULL
);

INSERT INTO palavras_cruzadas (palavra, dica) VALUES
('Formiga', 'Inseto que vive em sociedade'),
('Ensinar', 'Transmitir conhecimento'),
('Cinismo', 'Doutrina filosófica grega fundada por Antístenes'),
('Maconha', 'Planta de propriedades entorpecentes'),
('Carinho', 'Demonstração de zelo e cuidado, afago'),
('Soberba', 'Orgulho excessivo, arrogância'),
('Coragem', 'Postura de se manter firme, valentia'),
('Torpedo', 'Projétil usado contra alvos marinhos'),
('Intuito', 'Finalidade, propósito'),
('Anedota', 'História curta e engraçada'),
('Oneroso', 'Que envolve custo elevado'),
('Virtude', 'Em conformidade com o esperado'),
('Bizarro', 'Estranho, fora do comum'),
('Dirimir', 'Obter uma solução sobre'),
('Candura', 'Pureza, inocência, sinceridade'),
('Saudade', 'Sentir falta de algo ou alguém'),
('Parcial', 'Que não é completo'),
('Padecer', 'Sofrer dor ou angústia'),
('Canalha', 'Pessoa vil, desprezível'),
('Natural', 'Que pertence à natureza'),
('Abismal', 'Excessivamente profundo'),
('Quimera', 'Monstro mitológico formado por partes de animais'),
('Exilado', 'Expulso ou afastado de algum lugar'),
('Sensato', 'Que goza de bom senso'),   
('Conciso', 'Resumido, sintético, enxuto'),
('Mancebo', 'Rapaz jovem'),
('Austero', 'Inflexível em opiniões e comportamentos'),
('Ousadia', 'Insolência, ambição'),
('Desafio', 'Grande obstáculo, disputa'),
('Singelo', 'Excessivamente simples'),
('Ventura', 'Sorte, destino favorável'),
('Sincero', 'Que expressa honestidade'),
('Censura', 'Controle da informação, veto'),
('Sentido', 'Percepção, significado'),
('Apogeu', 'Ponto mais alto, ápice'),
('Alheio', 'Que diz respeito ao outro'),
('Abelha', 'Inseto que produz mel'),
('Rotina', 'Conjunto de hábitos repetidos diariamente'),
('Remoto', 'Distante no tempo ou espaço'),
('Rapina', 'Ave de ______, tipo de ave carnívora de bico adunco'),
('Omitir', 'Deixar de dizer algo, esconder'),
('Ofensa', 'Insulto, injúria'),
('Oposto', 'Que faz oposição'),
('Adorno', 'Theodor ______, filósofo membro da escola de Frankfurt'),
('Astuto', 'Esperto, sagaz'),
('Amigos', 'Companheiros, parceiros leais'),
('Online', 'Conectado à internet'),
('Oculto', 'Que está escondido'),
('Oferta', 'O que é oferecido');