CREATE DATABASE palavras_cruzadas;

USE palavras_cruzadas;

CREATE TABLE palavras_cruzadas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    palavra VARCHAR(7) NOT NULL,
    dica VARCHAR(50) NOT NULL
);

INSERT INTO palavras_cruzadas (palavra, dica) VALUES
('Formiga', 'Inseto que vive em colônia'),
('Ensinar', 'Ato de transmitir conhecimento'),
('Cinismo', 'Falsa inocência ou descaramento'),
('Maconha', 'Substância feita de plantas'),
('Carinho', 'Afeto demonstrado com gestos'),
('Soberba', 'Orgulho excessivo, arrogância'),
('Coragem', 'Enfrentar o medo com bravura'),
('Torpedo', 'Arma disparada sob a água'),
('Intuito', 'Finalidade ou propósito'),
('Anedota', 'História curta e engraçada'),
('Oneroso', 'Que envolve custo elevado'),
('Virtude', 'Qualidade moral positiva'),
('Bizarro', 'Estranho ou fora do comum'),
('Dirimir', 'Resolver um conflito'),
('Candura', 'Pureza, inocência, sinceridade'),
('Saudade', 'Sentir falta de algo ou alguém'),
('Parcial', 'Que não é imparcial'),
('Padecer', 'Sofrer dor ou angústia'),
('Canalha', 'Pessoa vil e desprezível'),
('Natural', 'Que não é artificial'),
('Abismal', 'Extremamente profundo'),
('Quimera', 'Ilusão ou fantasia irreal'),
('Exilado', 'Expulso ou afastado do país'),
('Sensato', 'Que age com bom senso'),
('Consiso', 'Que fala com poucas palavras'),
('Mancebo', 'Rapaz jovem'),
('Austero', 'Rígido, sem luxo ou excessos'),
('Ousadia', 'Atitude corajosa e audaciosa'),
('Desafio', 'Prova que exige superação'),
('Singelo', 'Simples e bonito'),
('Ventura', 'Sorte ou destino favorável'),
('Sincero', 'Que fala com honestidade'),
('Censura', 'Reprovação ou veto'),
('Sentido', 'Percepção ou significado'),
('Tinhoso', 'Nome alternativo para o diabo'),
('Apogeu', 'Ponto mais alto de algo'),
('Alheio', 'Que pertence a outro'),
('Abelha', 'Inseto que produz mel'),
('Rotina', 'Hábito repetido diariamente'),
('Remoto', 'Distante no tempo ou espaço'),
('Rapina', 'Roubo violento ou ataque de ave'),
('Omitir', 'Deixar de dizer ou fazer algo'),
('Ofensa', 'Ato de insultar ou agredir'),
('Oposto', 'Totalmente contrário'),
('Adorno', 'Objeto usado para enfeitar'),
('Astuto', 'Esperto, sagaz'),
('Amigos', 'Companheiros, parceiros leais'),
('Online', 'Conectado à internet'),
('Oculto', 'Que está escondido'),
('Oferta', 'Promoção ou proposta de compra');